// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAmounts() {
  return window['go']['main']['App']['LoadAmounts']();
}

export function ManualPumpControl(arg1) {
  return window['go']['main']['App']['ManualPumpControl'](arg1);
}

export function PourByBarcode(arg1) {
  return window['go']['main']['App']['PourByBarcode'](arg1);
}

export function PourCocktail(arg1) {
  return window['go']['main']['App']['PourCocktail'](arg1);
}

export function ProcessPour(arg1) {
  return window['go']['main']['App']['ProcessPour'](arg1);
}

export function SaveAmounts(arg1) {
  return window['go']['main']['App']['SaveAmounts'](arg1);
}
