// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadAmounts():Promise<Record<string, number>>;

export function ManualPumpControl(arg1:number):Promise<void>;

export function PourByBarcode(arg1:string):Promise<main.OrderResponse>;

export function PourCocktail(arg1:number):Promise<main.OrderResponse>;

export function ProcessPour(arg1:number):Promise<string>;

export function SaveAmounts(arg1:Record<string, number>):Promise<void>;
